language: minimal
services:
  - docker

stages:
    - build
    - pgpsign
    - name: makerelease
      if: tag IS present

jobs:
  include:
    - stage: build
      env: RID=debian-x64
      script: ./Build/travis/build.sh
    -
      env: RID=linux-x64
      script: ./Build/travis/build.sh
    - 
      env: RID=osx-x64
      script: ./Build/travis/build.sh
    -
      env: RID=win-x64
      script: ./Build/travis/build.sh

    - stage: pgpsign
      script: ./Build/travis/pgpsign.sh
    - stage: makerelease
      script: ./Build/travis/makerelease.sh
