language: minimal
services:
  - docker
stages:
  - build

env:
  jobs:
    - RID=debian-x64
    - RID=linux-x64
    - RID=osx-x64
    - RID=win-x64

jobs:
  include:
    - stage: build
      name: "Building in docker for $RID"
      script: cd Build/ && docker build -t "vault-$RID" -f "$RID/Dockerfile" ..
