language: minimal
services:
  - docker
stages:
  - build

jobs:
  include:
    - stage: build
      name: "Create .deb"
      env: RID=debian-x64
    - stage: build
      name: "Create .tar.gz"
      env: RID=linux-x64
    - stage: build
      name: "Create .dmg"
      env: RID=osx-x64
    - stage: build
      name: "Create setup.exe"
      env: RID=win-x64

script: cd Build/ && docker build -t "vault-$RID" -f "$RID/Dockerfile" ..
